import Head from 'next/head'
import Link from 'next/link';
import GlobalStyles from "../styles/globals.styles"
import {
  Top, Search, SearchBox, SearchIcon, Filter, Countries, CountriesBox, Country, Flag,
  Description, Bold, Dropdown, ErrorMessage, Btn, PageNumbers, Pagination
} from '../styles/main.styles'
import { BiSearch } from "react-icons/bi"
import { IoIosArrowDown } from "react-icons/io"
import { GrFormNext, GrFormPrevious } from "react-icons/gr"
import useSWR from 'swr';
import { useState } from "react"
import Header from "../component/Header"

const fetcher = (url: RequestInfo | URL) => fetch(url).then((res) => res.json()).then((res) => JSON.parse(res));

interface CountryProps {
  name: string,
  nativeName: string,
  population: number,
  region: string
  subregion: string,
  capital: string,
  flag: string,
}

export default function Home() {
  const [search, setSearch] = useState<string>("")
  const [region, setRegion] = useState<string>("")
  const [inputValue, setInputValue] = useState<string>("")
  const [dropdown, setDropdown] = useState<boolean>(false)
  const { data, error } = useSWR<CountryProps[], Error>('/api/staticdata', fetcher)
  const [currentPage, SetCurrentPage] = useState<number>(1)

  const PostPerPage: number = 13
  const endIndex: number = currentPage * PostPerPage
  const startIndex: number = endIndex - PostPerPage
  const currentPost = data?.slice(startIndex, endIndex)
  console.log(endIndex, startIndex, currentPost)
  const pageNumbers: number[] = []
  console.log(data?.length, typeof (data))
  const maxPageNumbers = Math.ceil(250 / PostPerPage)
  for (let i = 1; i <= maxPageNumbers; i++) {
    pageNumbers.push(i)
  }

  function changePageNumber() {
    if (currentPage > pageNumbers.length) {
      SetCurrentPage(currentPage => currentPage - 1)
    }
    if (currentPage < pageNumbers.length) {
      SetCurrentPage(currentPage => currentPage + 1)
    }
    else {
      SetCurrentPage(1)
    }
  }

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const value = e.target.value
    const firstLetter = value.charAt(0)
    const capitalLetter = firstLetter.toUpperCase()
    const otherLetters = value.slice(1)
    const countryName = capitalLetter + otherLetters
    console.log(countryName)
    setInputValue(countryName)
    countryName.length === 0 && setSearch("")
  }

  function handleKey(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter') {
      setSearch(inputValue)
    }
  }

  function showDropdown() {
    setDropdown(prevValue => !prevValue)
  }

  function showCountries(name: string) {
    if (name === "All") {
      setRegion("")
    }
    else {
      setRegion(name)
    }
  }
  console.log(region)

  if (error) return <p>Failed to load</p>
  if (!data) return <p>Loading...</p>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <GlobalStyles />
      <Header />
      <main>
        <Top>
          <Search>
            <SearchBox
              type='text' placeholder='Search for a country...' onChange={handleChange} onKeyDown={handleKey}>
            </SearchBox>
            <SearchIcon>
              <BiSearch />
            </SearchIcon>
          </Search>
          <Filter>
            <p>Filter by Region</p>
            <div><IoIosArrowDown onClick={showDropdown} /></div>
          </Filter>
          {dropdown &&
            <Dropdown>
              <li onClick={() => showCountries('All')}>All</li>
              <li onClick={() => showCountries('Africa')}>Africa</li>
              <li onClick={() => showCountries('Americas')}>America</li>
              <li onClick={() => showCountries('Asia')}>Asia</li>
              <li onClick={() => showCountries('Europe')}>Europe</li>
              <li onClick={() => showCountries('Oceania')}>Oceania</li>
            </Dropdown>
          }
        </Top>
        {search.length === 0 && region.length === 0 ?
          <Countries>
            {currentPost?.map((country) =>
              <Link href={"/posts/" + country.name} >
                <Country key={country.name}>
                  <Flag src={country.flag} alt="flag" width={250} height={150} />
                  <Description>
                    <h2>{country.name}</h2>
                    <p><Bold>Population: </Bold>{country.population}</p>
                    <p><Bold>Region: </Bold>{country.region}</p>
                    <p><Bold>Capital: </Bold>{country.capital}</p>
                  </Description>
                </Country>
              </Link>
            )}
            <Pagination>
              <Btn onClick={changePageNumber}>
                <GrFormPrevious />
              </Btn>
              <PageNumbers>
                {pageNumbers.map(pageNumber =>
                  <div key={pageNumber} onClick={() => { SetCurrentPage(pageNumber) }} 
                  style={{fontWeight: pageNumber === currentPage? 600 : 200}}>
                    {pageNumber}
                  </div>)}
              </PageNumbers>
              <Btn onClick={changePageNumber}>
                <GrFormNext />
              </Btn>
            </Pagination>
          </Countries>
          :
          <CountriesBox>{
            region.length > 0 ?
              currentPost?.filter(country => country.region === region).map(country => country.name.includes(search) &&
                <Link href={"/posts/" + country.name} >
                  <Country key={country.name}>
                    <Flag src={country.flag} alt="flag" width={250} height={150} />
                    <Description>
                      <h2>{country.name}</h2>
                      <p><Bold>Population: </Bold>{country.population}</p>
                      <p><Bold>Region: </Bold>{country.region}</p>
                      <p><Bold>Capital: </Bold>{country.capital}</p>
                    </Description>
                  </Country>
                </Link>
              ) :
              currentPost?.map(country => country.name.includes(search) &&
                <Link href={"/posts/" + country.name} >
                  <Country key={country.name}>
                    <Flag src={country.flag} alt="flag" width={250} height={150} />
                    <Description>
                      <h2>{country.name}</h2>
                      <p><Bold>Population: </Bold>{country.population}</p>
                      <p><Bold>Region: </Bold>{country.region}</p>
                      <p><Bold>Capital: </Bold>{country.capital}</p>
                    </Description>
                  </Country>
                </Link>
              )}
            <Pagination>
              <Btn onClick={changePageNumber}>
                <GrFormPrevious />
              </Btn>
              <PageNumbers>
                {pageNumbers.map(pageNumber =>
                  <div key={pageNumber} onClick={() => { SetCurrentPage(pageNumber) }}>
                    {pageNumber}
                  </div>)}
              </PageNumbers>
              <Btn onClick={changePageNumber}>
                <GrFormNext />
              </Btn>
            </Pagination>
          </CountriesBox>
        }
      </main>
    </>
  )
}
