import Head from 'next/head'
import Link from 'next/link';
import GlobalStyles from "../styles/globals.styles"
import {
  Top, Search, SearchBox, SearchIcon, Filter, Countries, Country, Flag,
  Description, Bold, Dropdown, Btn, PageNumbers, Pagination, ErrorMessage
} from '../styles/main.styles'
import { BiSearch } from "react-icons/bi"
import { IoIosArrowDown } from "react-icons/io"
import { GrFormNext, GrFormPrevious } from "react-icons/gr"
import useSWR from 'swr';
import { useState, useEffect } from "react"
import Header from "../component/Header"

const fetcher = (url: RequestInfo | URL) => fetch(url).then((res) => res.json()).then((res) => JSON.parse(res));

interface CountryProps {
  name: string,
  nativeName: string,
  population: number,
  region: string
  subregion: string,
  capital: string,
  flag: string,
}

export default function Home() {
  const [search, setSearch] = useState<string>("")
  const [region, setRegion] = useState<string>("All")
  const [errorMessage, setErrorMessage] = useState<boolean>(false)
  const [dropdown, setDropdown] = useState<boolean>(false)
  const { data: postData, error } = useSWR<CountryProps[], Error>('/api/staticdata', fetcher)
  const data = postData || [];
  const [currentPage, SetCurrentPage] = useState<number>(1)
  const [filteredPost, setFilteredPost] = useState(data)

  const postPerPage = 13
  const endIndex = currentPage * postPerPage
  const startIndex = endIndex - postPerPage
  const filteredPostData = filteredPost.length > 0 ? filteredPost.slice(startIndex, endIndex) : data.slice(startIndex, endIndex)
  console.log(endIndex, startIndex, filteredPostData)
  const pageNumbers = []
  const dataLength = filteredPost.length > 0 ? filteredPost.length : data.length
  const maxPageNumbers = Math.ceil(dataLength / postPerPage)
  for (let i = 1; i <= maxPageNumbers; i++) {
    pageNumbers.push(i)
  }

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const value = e.target.value
    const firstLetter = value.charAt(0)
    const capitalLetter = firstLetter.toUpperCase()
    const otherLetters = value.slice(1)
    const countryName = capitalLetter + otherLetters
    console.log(countryName)
    if (countryName.length === 0) {
      setSearch("")
    }
    else {
      setSearch(countryName)
    }
    // data.map(country => country.name.includes(search)? setErrorMessage(false) : setErrorMessage(true))
    console.log(errorMessage)
  }

  function showDropdown() {
    setDropdown(prevValue => !prevValue)
  }

  function showCountries(name: string) {
    if (name === "All") {
      setFilteredPost(data)
      setRegion("All")
    }
    else {
      const post = data.filter(country => country.region === name)
      setFilteredPost(post)
      setRegion(name)
    }
    setDropdown(false)
    SetCurrentPage(1)
  }

  function setNextPage() {
    if (currentPage === pageNumbers.length) {
      SetCurrentPage(1)
    }
    else {
      SetCurrentPage(currentPage => currentPage + 1)
    }
  }

  if (error) return <p>Failed to load</p>
  if (!data) return <p>Loading...</p>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />
      <Header />
      <main>
        <Top>
          <Search>
            <SearchBox
              type='text' placeholder='Search for a country...' onChange={handleChange}>
            </SearchBox>
            <SearchIcon>
              <BiSearch />
            </SearchIcon>
          </Search>
          <Filter onClick={showDropdown}>
            <p>Filter by Region</p>
            <div><IoIosArrowDown /></div>
          </Filter>
          {dropdown &&
            <Dropdown>
              <li onClick={() => showCountries('All')}>All</li>
              <li onClick={() => showCountries('Africa')}>Africa</li>
              <li onClick={() => showCountries('Americas')}>America</li>
              <li onClick={() => showCountries('Asia')}>Asia</li>
              <li onClick={() => showCountries('Europe')}>Europe</li>
              <li onClick={() => showCountries('Oceania')}>Oceania</li>
            </Dropdown>
          }
        </Top>
        <Countries>
          {search === "" ?
            filteredPostData.map((country) =>
              <Link href={"/posts/" + country.name} key={country.name} >
                <Country>
                  <Flag src={country.flag} alt="flag" width={250} height={150} />
                  <Description>
                    <h2>{country.name}</h2>
                    <p><Bold>Population: </Bold>{country.population}</p>
                    <p><Bold>Region: </Bold>{country.region}</p>
                    <p><Bold>Capital: </Bold>{country.capital}</p>
                  </Description>
                </Country>
              </Link>
            )
            :
            region === "All"?
            data.map(country => country.name.includes(search) &&
              <Link href={"/posts/" + country.name} key={country.name}>
                <Country>
                  <Flag src={country.flag} alt="flag" width={250} height={150} />
                  <Description>
                    <h2>{country.name}</h2>
                    <p><Bold>Population: </Bold>{country.population}</p>
                    <p><Bold>Region: </Bold>{country.region}</p>
                    <p><Bold>Capital: </Bold>{country.capital}</p>
                  </Description>
                </Country>
              </Link>
              ):
              filteredPost.map(country => country.name.includes(search) &&
              <Link href={"/posts/" + country.name} key={country.name}>
                <Country>
                  <Flag src={country.flag} alt="flag" width={250} height={150} />
                  <Description>
                    <h2>{country.name}</h2>
                    <p><Bold>Population: </Bold>{country.population}</p>
                    <p><Bold>Region: </Bold>{country.region}</p>
                    <p><Bold>Capital: </Bold>{country.capital}</p>
                  </Description>
                </Country>
              </Link>
              )

          }
          {errorMessage &&
            <ErrorMessage>
              <p>No result for "<span>{search}</span>"</p>
            </ErrorMessage>}
          {search === "" && <Pagination>
            <Btn onClick={() => SetCurrentPage(currentPage => currentPage - 1)}>
              <GrFormPrevious />
            </Btn>
            <PageNumbers>
              {pageNumbers.map(pageNumber =>
                <div key={pageNumber} onClick={() => { SetCurrentPage(pageNumber) }}
                  style={{ fontWeight: pageNumber === currentPage ? 600 : 200, cursor: 'pointer' }}>
                  {pageNumber}
                </div>)}
            </PageNumbers>
            <Btn onClick={setNextPage}>
              <GrFormNext />
            </Btn>
          </Pagination>
          }
        </Countries>
      </main>
    </>
  )
}
